<?php

namespace Techversed\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NavigationGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationGroupRepository extends EntityRepository
{
}
