techversed_main_homepage:
    path:     /
    defaults: { _controller: TechversedMainBundle:Home:index }

techversed_hello_test:
    path:     /hello/{name}
    defaults: { _controller: TechversedMainBundle:Default:index }

navigation_group_query:
    path:     /api/v1/navigation-group
    defaults:
        _controller: TechversedMainBundle:NavigationGroup:query
    requirements:
        _method: get
